import { useMemo } from 'react';
import { jsPDF } from 'jspdf';
import { getStreak, loadDays, todayStr } from '../../lib/rewards';

export function DayReport({ completed, focusMin, profileName = 'Pomo' }) {
  const days = useMemo(() => loadDays(), [completed]);
  const today = days[todayStr()] || 0;
  const streak = getStreak(days);
  const focusTodayMin = today * focusMin;
  const totalPomos = Object.values(days).reduce((s, n) => s + n, 0);
  const totalMin = totalPomos * focusMin;
  const best = Math.max(0, ...Object.values(days));
  const score = today >= 8 ? 'Elite' : today >= 4 ? 'Great' : today >= 1 ? 'Warming up' : 'Rest day';
  const entries = Object.entries(days).sort().slice(-14);

  const pdf = () => {
    const doc = new jsPDF();
    const W = 210;
    // header band
    doc.setFillColor(255, 77, 77);
    doc.rect(0, 0, W, 42, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.text('Pomo Focus — Day Report', 14, 18);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.text(`${todayStr()}  •  ${profileName}  •  ${focusMin} min per pomodoro`, 14, 28);
    doc.text(`Score of the day: ${score}`, 14, 35);

    // stat cards
    const stats = [
      [`${focusTodayMin}m`, 'Focus today'],
      [`${today}`, 'Pomodoros'],
      [`${streak} days`, 'Streak'],
      [`${totalMin}m`, 'All-time focus'],
      [`${best}`, 'Best day'],
      [`${totalPomos}`, 'Lifetime pomodoros'],
    ];
    let y = 52;
    doc.setFontSize(11);
    stats.forEach(([v, l], i) => {
      const col = i % 3;
      const row = Math.floor(i / 3);
      const x = 14 + col * 62;
      const yy = y + row * 26;
      doc.setFillColor(255, 247, 247);
      doc.roundedRect(x, yy, 58, 21, 3, 3, 'F');
      doc.setTextColor(30, 20, 15);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.text(String(v), x + 5, yy + 9);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(120, 110, 100);
      doc.text(l, x + 5, yy + 16);
    });

    // daily table
    y = y + 58;
    doc.setTextColor(30, 20, 15);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.text('Last 14 days', 14, y);
    y += 4;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.setFillColor(25, 25, 25);
    doc.rect(14, y, 182, 8, 'F');
    doc.text('Date', 18, y + 6);
    doc.text('Pomodoros', 90, y + 6);
    doc.text('Focus (min)', 150, y + 6);
    y += 8;
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(30, 20, 15);
    if (!entries.length) {
      doc.text('No sessions yet — start your first pomodoro!', 18, y + 6);
      y += 8;
    }
    entries.forEach(([d, n], i) => {
      if (i % 2 === 0) {
        doc.setFillColor(255, 240, 238);
        doc.rect(14, y, 182, 8, 'F');
      }
      doc.text(d, 18, y + 6);
      doc.text(String(n), 90, y + 6);
      doc.text(String(n * focusMin), 150, y + 6);
      y += 8;
    });

    // footer
    doc.setFontSize(9);
    doc.setTextColor(150, 140, 130);
    doc.text('Focus. Break. Repeat. — generated by Pomo Focus', 14, 288);
    doc.save(`pomo-report-${todayStr()}.pdf`);
  };

  return (
    <div className="prod-box">
      <div className="rew-head">
        <h2>📊 Day report</h2>
        <button onClick={pdf}>⬇ PDF</button>
      </div>
      <div className="rew-stats">
        <div className="stat"><b>{focusTodayMin}m</b><span>focus today</span></div>
        <div className="stat"><b>{today}</b><span>pomodoros</span></div>
        <div className="stat"><b>🔥{streak}</b><span>streak</span></div>
        <div className="stat"><b>{totalMin}m</b><span>all-time</span></div>
      </div>
      <small className="muted">Best day: {best} 🍅 • {focusMin} min per pomo • Score: {today >= 8 ? 'Elite 🏆' : today >= 4 ? 'Great 💪' : today >= 1 ? 'Warming up 🌱' : 'Rest day 😴'}</small>
    </div>
  );
}
